=== MolSSI-BSE/basis_set_exchange/basis_set_exchange/schema/metadata-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "name": "bse_basis_metadata",
    "version": "0.1",
    "url": "TODO",
    "description": "JSON for describing metadata for a single basis set",
    "type": "object",
    "additionalProperties": false,
    "required": [
        "molssi_bse_schema",
        "names",
        "tags",
        "family",
        "description",
        "role",
        "auxiliaries"
    ],
    "properties":
    {
        "molssi_bse_schema": {
            "description": "Info about which schema the file follows",
            "type": "object",
            "additionalProperties": false,
            "required": [
                "schema_type",
                "schema_version"
            ],
            "properties": {
                "schema_type" : {
                    "description": "What type of BSE JSON file this is",
                    "type": "string",
                    "enum": [ "metadata" ]
                },
                "schema_version": {
                    "description": "Version of the BSE table basis set schema being used",
                    "type": "string"
                }
            }
        },
        "names": {
            "description": "Common names/capitalization of the basis set",
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": { "type": "string" }
        },
        "tags": {
            "description": "Feature tags (for internal use/marking)",
            "type": "array",
            "uniqueItems": true,
            "items": {
                "type": "string",
                "enum": ["deprecated"]
            }
        },
        "family": {
            "description": "Broad family that the basis set is from",
            "type": "string"
        },
        "description": {
            "description": "Brief description of the basis set",
            "type": "string"
        },
        "role": {
            "description": "Role that this basis plays in a calculation",
            "type": "string",
            "enum": [ "orbital", "rifit", "optri", "jkfit", "jfit", "admmfit", "dftxfit", "dftjfit"]
        },
        "auxiliaries": {
            "description": "Auxiliary basis sets (fitting, etc) and how their role with this basis",
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "jfit" : { "type": "string" },
                "jkfit" : { "type": "string" },
                "rifit" : { "type": "string" },
                "optri" : { "type": "string" },
                "admmfit" : { "type": "string" },
                "dftxfit": { "type": "string" },
                "dftjfit": { "type": "string" }
            }
        }
    }
}

=== MolSSI-BSE/basis_set_exchange/basis_set_exchange/data/tzvp-molopt-uzh-pbe0-gth-q11.metadata.json
{
  "molssi_bse_schema": {
    "schema_type": "metadata",
    "schema_version": "0.1"
  },
  "names": [
    "TZVP-MOLOPT-UZH-PBE0-GTH-q11",
    "TZVP-MOLOPT-PBE0-GTH-q11",
    "TZVP-MOLOPT-HYB-GTH-q11"
  ],
  "tags": [],
  "family": "molopt_uzh",
  "description": "UZH protocol GTH orbital basis (TZVP-MOLOPT-PBE0-GTH-q11)",
  "role": "orbital",
  "auxiliaries": {}
}

=== MolSSI-BSE/basis_set_exchange/basis_set_exchange/data/cc-pVTZ-F12.metadata.json
{
  "molssi_bse_schema": {
    "schema_type": "metadata",
    "schema_version": "0.1"
  },
  "names": [
    "cc-pVTZ-F12"
  ],
  "tags": [],
  "family": "dunning_f12",
  "description": "VTZ for explicitly correlated F12 variants of wavefunction methods",
  "role": "orbital",
  "auxiliaries": {
    "optri": "cc-pvtz-f12-optri"
  }
}

=== MolSSI-BSE/basis_set_exchange/basis_set_exchange/data/6-31GS.metadata.json
{
    "molssi_bse_schema": {
        "schema_type": "metadata",
        "schema_version": "0.1"
    },
    "names": [
        "6-31G*",
        "6-31G(d)"
    ],
    "tags": [],
    "family": "pople",
    "description": "6-31G + polarization on heavy atoms",
    "role": "orbital",
    "auxiliaries": {}
}

=== MolSSI-BSE/basis_set_exchange/basis_set_exchange/data/qzvpp-molopt-uzh-pbe-gth-q11.metadata.json
{
  "molssi_bse_schema": {
    "schema_type": "metadata",
    "schema_version": "0.1"
  },
  "names": [
    "QZVPP-MOLOPT-UZH-PBE-GTH-q11",
    "QZVPP-MOLOPT-PBE-GTH-q11",
    "QZVPP-MOLOPT-GGA-GTH-q11"
  ],
  "tags": [],
  "family": "molopt_uzh",
  "description": "UZH protocol GTH orbital basis (QZVPP-MOLOPT-PBE-GTH-q11)",
  "role": "orbital",
  "auxiliaries": {}
}

=== MolSSI-BSE/basis_set_exchange/basis_set_exchange/data/dzvp-molopt-uzh-pbe0-gth-q5.metadata.json
{
  "molssi_bse_schema": {
    "schema_type": "metadata",
    "schema_version": "0.1"
  },
  "names": [
    "DZVP-MOLOPT-UZH-PBE0-GTH-q5",
    "DZVP-MOLOPT-PBE0-GTH-q5",
    "DZVP-MOLOPT-HYB-GTH-q5"
  ],
  "tags": [],
  "family": "molopt_uzh",
  "description": "UZH protocol GTH orbital basis (DZVP-MOLOPT-PBE0-GTH-q5)",
  "role": "orbital",
  "auxiliaries": {}
}

=== MolSSI-BSE/basis_set_exchange/basis_set_exchange/data/dzvp-molopt-uzh-pbe-gth-q14.metadata.json
{
  "molssi_bse_schema": {
    "schema_type": "metadata",
    "schema_version": "0.1"
  },
  "names": [
    "DZVP-MOLOPT-UZH-PBE-GTH-q14",
    "DZVP-MOLOPT-PBE-GTH-q14",
    "DZVP-MOLOPT-GGA-GTH-q14"
  ],
  "tags": [],
  "family": "molopt_uzh",
  "description": "UZH protocol GTH orbital basis (DZVP-MOLOPT-PBE-GTH-q14)",
  "role": "orbital",
  "auxiliaries": {}
}

=== MolSSI-BSE/basis_set_exchange/basis_set_exchange/data/tzvp-molopt-uzh-pbe-gth-q8.metadata.json
{
  "molssi_bse_schema": {
    "schema_type": "metadata",
    "schema_version": "0.1"
  },
  "names": [
    "TZVP-MOLOPT-UZH-PBE-GTH-q8",
    "TZVP-MOLOPT-PBE-GTH-q8",
    "TZVP-MOLOPT-GGA-GTH-q8"
  ],
  "tags": [],
  "family": "molopt_uzh",
  "description": "UZH protocol GTH orbital basis (TZVP-MOLOPT-PBE-GTH-q8)",
  "role": "orbital",
  "auxiliaries": {}
}

=== MolSSI-BSE/basis_set_exchange/basis_set_exchange/data/tzvpp-molopt-uzh-pbe-gth-q17.metadata.json
{
  "molssi_bse_schema": {
    "schema_type": "metadata",
    "schema_version": "0.1"
  },
  "names": [
    "TZVPP-MOLOPT-UZH-PBE-GTH-q17",
    "TZVPP-MOLOPT-PBE-GTH-q17",
    "TZVPP-MOLOPT-GGA-GTH-q17"
  ],
  "tags": [],
  "family": "molopt_uzh",
  "description": "UZH protocol GTH orbital basis (TZVPP-MOLOPT-PBE-GTH-q17)",
  "role": "orbital",
  "auxiliaries": {}
}
